# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: fantojava.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: postgres://npoaamsmljfrkn:2b03b5549b67645f7317e845d4f04028392d9d874bf1af43d91453588d4a11bf@ec2-23-21-166-148.compute-1.amazonaws.com:5432/d7vmmlcqmvksir
        username: npoaamsmljfrkn
        password: 2b03b5549b67645f7317e845d4f04028392d9d874bf1af43d91453588d4a11bf
        hikari:
            maximumPoolSize: 8
