version: '2'
services:
    roombooking-app:
        image: roombooking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://roombooking-postgresql:5432/roombooking
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    roombooking-postgresql:
        extends:
            file: postgresql.yml
            service: roombooking-postgresql
