version: '2'
services:
    roombooking-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/roombooking/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=roombooking
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
